[SW-26] Menu is overlapping
svekukucska/starwars-react pull request #16
Opened 2019-10-09 15:45 UTC by svekukucska

- Fixed responsive main menu on medium & small devices (made the menu toggle when an item is clicked)

2019-10-09 16:21 UTC, spinenco-sv requested changes

2019-10-09 16:21 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> +  toggleMainMenu = () => {
let's rename this to something more relevant like: closeMainMenu?

2019-10-09 16:21 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> +      this.props.history.push('/movies');
Can you please move this into a separated function?

2019-10-09 16:21 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> +              <NavDropdown id={'myLinks'} variant="tabs" title={linkMovieList} onMouseEnter={this.handleDropdownOpen} onMouseLeave={this.handleDropdownClose} show={dropdownOpen}>
do you need this id?

2019-10-09 16:21 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> -          <Navbar.Collapse id="responsive-navbar-nav">
you need this id for aria-controls, please add it back

2019-10-09 16:21 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> +                  <NavDropdown.Item as={NavLink} to={`/movies/${episode_id}`} key={episode_id} onClick={this.toggleMainMenu} >{title}</NavDropdown.Item>
Let's try to not have this type of lines, please add new lines here

2019-10-14 12:53 UTC, svekukucska commented
Requested changes have been implemented.

2019-10-15 07:19 UTC, spinenco-sv approved these changes

2019-10-15 07:20 UTC, merged