[Sw-29] Install and configure eslint
svekukucska/starwars-react pull request #20
Opened 2019-10-29 09:48 UTC by svIZsollei

2019-10-29 12:31 UTC, spinenco-sv requested changes

2019-10-29 12:31 UTC, spinenco-sv commented on src/components/MainMenu/index.js
> +
Please remove this space

2019-10-29 12:31 UTC, spinenco-sv commented on src/pages/Movie/index.js
> +    // console.log('blabla', this.props);
Please delete console.log

2019-10-29 14:38 UTC, spinenco-sv approved these changes

2019-10-29 15:21 UTC, svekozak requested changes

2019-10-29 15:21 UTC, svekozak commented on src/components/MainMenu/index.js
> +  Container, Navbar, Nav, NavDropdown,
@svIZsollei You can put each component name on a line of its own

2019-10-29 15:21 UTC, svekozak commented on src/components/MainMenu/index.js
>    handleDropdownClose = () => {
@svIZsollei Would you make the definition of handleDropdownClose and handleDropdownOpen consequent ?

2019-10-29 15:21 UTC, svekozak commented on src/components/MainMenu/index.js
> +    const linkMovieList = (<span onClick={this.goToMovieList} onKeyPress={() => {}} role="link" tabIndex="0"> Star Wars Movies</span>);
@svIZsollei @svekukucska please, look into this onKeyPress

2019-10-29 15:21 UTC, svekozak commented on src/helpers/date.js
> +    const dateFull = isValidDate(dateObject) ? `${dateObject.getDate()} ${dateObject.toLocaleString('default', { month: 'long' })} ${dateObject.getFullYear()}` : '';
@svIZsollei you can return directly the value (the local variable is redundant). Also the line length is longer than 120 characters. Please, format code.

2019-10-29 15:21 UTC, svekozak commented on src/pages/Movie/index.js
> +      title, releaseDate, director, openingCrawl,
@svIZsollei each attribute on new line, please

2019-10-30 17:05 UTC, svekozak approved these changes
👍

2019-10-30 17:05 UTC, merged