[SW-8] Add a fixed main menu
svekukucska/starwars-react pull request #3
Opened 2019-09-25 07:45 UTC by svekukucska

2019-09-26 11:26 UTC, svekozak requested changes

2019-09-26 11:26 UTC, svekozak commented on public/index.html
> +</html>
New line, please

2019-09-26 11:26 UTC, svekozak commented on public/index.html
> +<head>
Indentation

2019-09-26 11:26 UTC, svekozak commented on public/index.html
> +<body>
Indentation

2019-09-26 11:26 UTC, svekozak commented on src/App.css
> +	}
Indentation

2019-09-26 11:26 UTC, svekozak commented on src/modules/MainMenu/index.js
> +                  <Nav.Link href="#">Star Wars Movies</Nav.Link>
missing URLs

2019-09-26 11:26 UTC, svekozak commented on src/pages/NotFound/index.js
> +const NotFound = (props) => <h1 className="route-padding">NotFound - Error 404!!</h1>;
What about adding a container in the App.js and applying the padding on that - so it would apply to all pages?

2019-09-26 11:26 UTC, svekozak commented on src/App.css
> +	padding-top: 15vh;
@svekukucska Let's not use viewport units

2019-09-26 11:26 UTC, svekozak commented on src/App.css
>  .App-logo {
@svekukucska You should remove the classes which are not used anymore

2019-09-26 11:26 UTC, svekozak commented on src/modules/MainMenu/index.js
> +                <Nav className="mr-auto main-menu-2">
Remove "mr-auto" class in order for the items to align left, or replace with "m-auto" to align center.

2019-09-26 12:35 UTC, svekukucska commented on public/index.html
> +</html>
Introduced new line after last line of code.

2019-09-27 07:17 UTC, svekozak requested changes

2019-09-27 07:17 UTC, svekozak commented on src/modules/MainMenu/index.js
> +import { Navbar, Nav } from 'react-bootstrap';
```import { NavLink } from 'react-router-dom';```

2019-09-27 07:17 UTC, svekozak commented on src/modules/MainMenu/index.js
> +                  <Nav.Link href="/movies">Star Wars Movies</Nav.Link>
```<Nav.Link as={NavLink} to="/movies">```

2019-09-27 07:40 UTC, svekozak approved these changes
🆗

2019-09-27 07:40 UTC, merged