Sw 20 refactor star wars movie list page to use redux
svekukucska/starwars-react pull request #30
Opened 2019-12-17 07:02 UTC by svIZsollei

2019-12-19 15:18 UTC, svekukucska approved these changes

2020-01-07 12:53 UTC, spinenco-sv commented
@svIZsollei Please resolve conflicts

2020-01-07 12:54 UTC, spinenco-sv commented on src/pages/StarWarsMovies/index.js
> +  getMovies: propTypes.func,
please make this function required

2020-01-08 09:27 UTC, spinenco-sv requested changes

2020-01-08 09:27 UTC, spinenco-sv commented on src/actions/movies.js
> +  results: movies,
you can rename the **movies** parameter to **results**

2020-01-08 09:27 UTC, spinenco-sv commented on src/reducers/movies.js
> +  movies: [{ id: 1 }],
Please remove { id: 1 }

2020-01-08 11:41 UTC, spinenco-sv approved these changes

2020-01-08 11:41 UTC, merged