[SW-33] Refactor movies reducers into one reducer
svekukucska/starwars-react pull request #31
Opened 2020-01-14 09:00 UTC by svIZsollei

2020-01-14 09:28 UTC, spinenco-sv approved these changes

2020-01-14 12:03 UTC, svekozak requested changes

2020-01-14 12:03 UTC, svekozak commented on src/actions/fetching.js
> +export const isFetching = (item, value) => (dispatch) => {
@svekukucska @svIZsollei  Where do we use this ?

2020-01-14 12:03 UTC, svekozak commented on src/actions/movies.js
>    type: 'TAKE_MOVIES',
@svekukucska @svIZsollei why don't we use the constant instead?

2020-01-14 12:03 UTC, svekozak commented on src/pages/StarWarsMovies/index.js
> +  getMovies: () => dispatch(fetchMovies()),
This should be replaced by:
```
const mapDispatchToProps = {
  getMovies : fetchMovies,
};
```
@svekukucska @svIZsollei

2020-01-15 09:54 UTC, svekozak approved these changes

2020-01-15 09:54 UTC, merged