[SW-35] Refactor Planets Component with Redux
svekukucska/starwars-react pull request #35
Opened 2020-02-25 13:58 UTC by svekukucska

2020-02-25 14:58 UTC, spinenco-sv requested changes

2020-02-25 14:58 UTC, spinenco-sv commented on src/components/Planet/index.js
>      const id = getIdFromUrl(planetUrl);
Instead of getting the id from url, we can now extract it from redux

2020-02-25 15:35 UTC, spinenco-sv approved these changes

2020-02-28 11:59 UTC, svekozak approved these changes
🐟

2020-02-28 12:00 UTC, merged